version: '3.4'

services:
  cardapio:
    image: cardapio
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      hostname: 0.0.0.0
      port: 3000
    ports:
      - 3000:3000
